### ISSUE TITLE
Patch doesnt apply to kernel version 4.10.0

### ISSUE THREAD

**Issue by vennand** [IPv6-mPvD/pvd-linux-kernel-patch#1]
Hi,

Following on from the IETF Hackathon, I am trying to get your PvD patch
set working on a raspberry pi 3.

Trying to build the Ubuntu kernel :
git clone git://kernel.ubuntu.com/ubuntu/ubuntu-zesty.git ubuntu-4.10.0
cd ubuntu-4.10.0
git checkout 56389f24b205f2464626d56bc15c5a6ceeeceedf

After applying this patch : https://github.com/IPv6-mPvD/pvd-linux-kernel-patch

Following the cross-compiling instructions of this guide : https://www.raspberrypi.org/documentation/linux/kernel/building.md

Using this configuration file : bcm2709_defconfig
Which had to be copied from Raspbian repository since it is not included by default in Ubuntu

After running this make command : make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs

I get this error :

CC [M] net/ipv6/addrconf.o
net/ipv6/addrconf.c: In function ‘ipv6_add_addr’:
net/ipv6/addrconf.c:1047:2: error: implicit declaration of function ‘pvd_migrate_addr’ [-Werror=implicit-function-declaration]
pvd_migrate_addr(pvd, ifa);
^
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target 'net/ipv6/addrconf.o' failed
make[2]: *** [net/ipv6/addrconf.o] Error 1
scripts/Makefile.build:567: recipe for target 'net/ipv6' failed
make[1]: *** [net/ipv6] Error 2
Makefile:1020: recipe for target 'net' failed
make: *** [net] Error 2

**Comment by Bloody95** [comment]
You need to activate the CONFIG_NETPVD flag in the config file.
That said, you are right : some pvd related calls are not properly enclosed in ifdefs.

I'll check it.

**Comment by vennand** [comment]
It fixed that error.

However, I have another error now

OBJCOPY arch/arm/boot/zImage
  Kernel: arch/arm/boot/zImage is ready
  Building modules, stage 2.
  MODPOST 1475 modules
ERROR: "pvd_register_dnssl" [net/ipv6/ipv6.ko] undefined!
ERROR: "pvd_register_rdnss" [net/ipv6/ipv6.ko] undefined!
ERROR: "register_pvd" [net/ipv6/ipv6.ko] undefined!
ERROR: "pvd_rtnl_notify" [net/ipv6/ipv6.ko] undefined!
ERROR: "pvd_migrate_route" [net/ipv6/ipv6.ko] undefined!
ERROR: "pvd_migrate_addr" [net/ipv6/ipv6.ko] undefined!
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1
Makefile:1230: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by Bloody95** [comment]
I have committed a new patch protecting the use of pvd related functions + exporting the pvd functions in case the ipv6 core is compiled as a module.
The patch against a pristine kernel (still 4.10.7) is now in master branch, while the patch against the ubuntu zesty kernel is in the ubuntu-zesty branch

**Comment by vennand** [comment]
Great, both Ubuntu with the patch compiled.

The patch is also applied without issue to Raspbian (git clone --depth=1 https://github.com/raspberrypi/linux).
However, I get this error when trying to build (still using these instructions https://www.raspberrypi.org/documentation/linux/kernel/building.md)

  CC [M]  net/ipv6/route.o
net/ipv6/route.c: In function ‘rtm_to_fib6_config’:
net/ipv6/route.c:3067:9: error: ‘RTA_PVD’ undeclared (first use in this function)
  if (tb[RTA_PVD]) {
         ^
net/ipv6/route.c:3067:9: note: each undeclared identifier is reported only once for each function it appears in
net/ipv6/route.c: In function ‘rt6_fill_node’:
net/ipv6/route.c:3499:21: error: ‘RTA_PVD’ undeclared (first use in this function)
    if (nla_put(skb, RTA_PVD, strlen(pvdname) + 1, pvdname))
                     ^
scripts/Makefile.build:293: recipe for target 'net/ipv6/route.o' failed
make[2]: *** [net/ipv6/route.o] Error 1
scripts/Makefile.build:544: recipe for target 'net/ipv6' failed
make[1]: *** [net/ipv6] Error 2
Makefile:991: recipe for target 'net' failed
make: *** [net] Error 2

**Comment by Bloody95** [comment]
Hi,

Can you check the include/uapi/linux/rtnetlink.h file. The RTA_PVD value should be defined there,
along with the other RTA_XXX enums (search for the rtattr_type_t type definition).

**Comment by vennand** [comment]
Hello,

I edited the file rtnetlin.h, and added RTA_PVD in the rtattr_type_t enum since it was missing. The Raspbian with the patch now compiles and boots normally.

However, the pvdd client still outputs this:

./pvdd -v
Server port : 10101
Persistent directory : none defined
sizeof net_pvd_attribute = 3588
sizeof pvd_list = 262148
PVDNAMSIZ = 256
kernel_get_pvdlist: Protocol not available
++++ Assuming kernel not PvD aware
+++ Kernel  does not have PvD support

Anything else I could provide that might help solve this issue?

**Comment by vennand** [comment]
Nevermind, realized I forgot to enable the NET_PVD flag before building. Everything works now (patch from master branch works, build works, client works)

Thanks for your help

**Comment by Bloody95** [comment]
Did you have some patch conflicts that would have prevented the RTA_PVD definition to be added in the rtnetlnk.h file ?

**Comment by vennand** [comment]
Missed it the first time, but there was a problem during the patch

patching file include/uapi/linux/rtnetlink.h
Hunk #3 FAILED at 328.
Hunk #4 succeeded at 358 (offset -1 lines).
Hunk #5 succeeded at 553 (offset -1 lines).
Hunk #6 succeeded at 586 (offset -1 lines).
Hunk #7 succeeded at 606 (offset -1 lines).
Hunk #8 succeeded at 665 (offset -1 lines).
1 out of 8 hunks FAILED -- saving rejects to file include/uapi/linux/rtnetlink.h.rej


In the renetlink.h.rej:

--- include/uapi/linux/rtnetlink.h	2017-03-30 08:44:36.000000000 +0100
+++ include/uapi/linux/rtnetlink.h	2017-07-04 17:37:00.931584598 +0100
@@ -328,6 +337,8 @@
 	RTA_EXPIRES,
 	RTA_PAD,
 	RTA_UID,
+	RTA_TTL_PROPAGATE,
+	RTA_PVD,
 	__RTA_MAX
 };
